/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package mybankmachine;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Scanner;

/**
 *
 * @author DaTho7561
 */
public class MyBankMachine extends javax.swing.JFrame {

    String INVALID_INPUT_MESSAGE = "Please enter a number only.";
    
    ATM myBank;
    
    /**
     * Creates new form MyBankMachine
     */
    public MyBankMachine() {
        Scanner sc = new Scanner(System.in);
        double balance;
        String bankName;
        
        System.out.print("\nPlease enter the name of the bank: ");
        bankName = sc.nextLine();
        
        try {
            System.out.print("Please enter your initial balance: ");
            balance = sc.nextDouble();
            sc.nextLine();
            myBank = new ATM(balance, bankName);
        } catch (Exception e) {
            System.err.println("Invalid balance. Creating an empty bank account.");
            myBank = new ATM(bankName);
        }
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        logTextArea = new javax.swing.JTextArea();
        inputLabel = new javax.swing.JLabel();
        inputField = new javax.swing.JTextField();
        applyInterestButton = new javax.swing.JButton();
        withdrawButton = new javax.swing.JButton();
        depositButton = new javax.swing.JButton();
        logLabel = new javax.swing.JLabel();
        interestLabel = new javax.swing.JLabel();
        interestField = new javax.swing.JTextField();
        applyRateButton = new javax.swing.JButton();
        getBalanceButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titleLabel.setFont(new java.awt.Font("Ti86pc", 0, 36)); // NOI18N
        titleLabel.setText("ATM");

        logTextArea.setEditable(false);
        logTextArea.setColumns(20);
        logTextArea.setLineWrap(true);
        logTextArea.setRows(5);
        jScrollPane1.setViewportView(logTextArea);

        inputLabel.setText("Amount to change by:");

        applyInterestButton.setText("Apply Specified Days of Interest");
        applyInterestButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                applyInterestButtonActionPerformed(evt);
            }
        });

        withdrawButton.setText("Withdraw");
        withdrawButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                withdrawButtonActionPerformed(evt);
            }
        });

        depositButton.setText("Deposit");
        depositButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depositButtonActionPerformed(evt);
            }
        });

        logLabel.setText("Log -->");

        interestLabel.setText("Annual Interest Rate:");

        interestField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                interestFieldActionPerformed(evt);
            }
        });

        applyRateButton.setText("Apply new Rate");
        applyRateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                applyRateButtonActionPerformed(evt);
            }
        });

        getBalanceButton.setText("Print Balance");
        getBalanceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getBalanceButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(inputLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(inputField, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(logLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(interestLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(interestField)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(applyRateButton))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(depositButton)
                                .addGap(18, 18, 18)
                                .addComponent(withdrawButton)
                                .addGap(18, 18, 18)
                                .addComponent(applyInterestButton))
                            .addComponent(getBalanceButton, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(titleLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(logLabel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputLabel)
                    .addComponent(inputField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(applyInterestButton)
                    .addComponent(withdrawButton)
                    .addComponent(depositButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(interestLabel)
                    .addComponent(interestField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(applyRateButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(getBalanceButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void updateLog(String information) {
        Date d = new Date();
        DateFormat df = new SimpleDateFormat("dd/MM/yy HH:mm");
        logTextArea.setText(logTextArea.getText() + "[" + df.format(d) + "] " + information + "\n");
    }
    
    private void applyInterestButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_applyInterestButtonActionPerformed
        String daysString = inputField.getText();
        try {
            int days = Integer.parseInt(daysString);
            myBank.applyInterest(days);
            updateLog("Successfully added interest.");
        } catch(NumberFormatException nfe) {
            try {
                Double.parseDouble(daysString);
                System.err.println("Unable to calculate interest. Please enter a whole number.");
                updateLog("Unable to calculate interest. Please enter a whole number.");
            } catch (NumberFormatException nfe2) {
                System.err.println("Unable to calculate interest. " + INVALID_INPUT_MESSAGE);
                updateLog("Unable to calculate interest. " + INVALID_INPUT_MESSAGE);
            }
        }
        
        inputField.setText("");
    }//GEN-LAST:event_applyInterestButtonActionPerformed

    private void interestFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_interestFieldActionPerformed
        
        
        inputField.setText("");
    }//GEN-LAST:event_interestFieldActionPerformed

    private void depositButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depositButtonActionPerformed
        try {
            double amountToDeposit = Integer.parseInt(inputField.getText());
            myBank.deposit(amountToDeposit);
            updateLog("Deposited $" + amountToDeposit);
        } catch (NumberFormatException e) {
            System.err.println(INVALID_INPUT_MESSAGE);
            updateLog(INVALID_INPUT_MESSAGE);
        }
        
        inputField.setText("");
    }//GEN-LAST:event_depositButtonActionPerformed

    private void withdrawButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_withdrawButtonActionPerformed
        try {
            double amountToWithdraw = Integer.parseInt(inputField.getText());
            updateLog(myBank.withdraw(amountToWithdraw));
        } catch (NumberFormatException e) {
            System.err.println(INVALID_INPUT_MESSAGE);
            updateLog(INVALID_INPUT_MESSAGE);
        }
        
        inputField.setText("");
    }//GEN-LAST:event_withdrawButtonActionPerformed

    private void getBalanceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getBalanceButtonActionPerformed
        updateLog("Current balance is $" + myBank.getBalance());
    }//GEN-LAST:event_getBalanceButtonActionPerformed

    private void applyRateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_applyRateButtonActionPerformed
        String newInterestRateString = interestField.getText();
        
        try {
            double newInterestRate = Integer.parseInt(newInterestRateString);
            if (newInterestRate > 1) {
                System.err.println("Please input a decimal interest rate (below 1).");
                updateLog("Please input a decimal interest rate (below 1).");
            } else {
                myBank
            }
        } catch(NumberFormatException nfe){
            System.err.println(INVALID_INPUT_MESSAGE);
            updateLog(INVALID_INPUT_MESSAGE);
        }
    }//GEN-LAST:event_applyRateButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MyBankMachine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MyBankMachine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MyBankMachine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MyBankMachine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MyBankMachine().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton applyInterestButton;
    private javax.swing.JButton applyRateButton;
    private javax.swing.JButton depositButton;
    private javax.swing.JButton getBalanceButton;
    private javax.swing.JTextField inputField;
    private javax.swing.JLabel inputLabel;
    private javax.swing.JTextField interestField;
    private javax.swing.JLabel interestLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel logLabel;
    private javax.swing.JTextArea logTextArea;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JButton withdrawButton;
    // End of variables declaration//GEN-END:variables
}
